model:
  config_target: src.models.ldm_model_configs.ldmAEConfig
  monitor: "val/rec_loss"
#  embed_dim: 64

#  lossconfig:
#    target: ldm.modules.losses.LPIPSWithDiscriminator
#    disc_start: 50001
#    kl_weight: 0.000001
#    disc_weight: 0.5

  ddconfig:
    embed_dim: 64 # NL: moved this. Hopefully it doesn't cause pain
    double_z: True
    z_channels: 64
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [ 1,1,2,2,4,4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [16,8]
    dropout: 0.0

  dataconfig:
#    target: main.DataModuleFromConfig
    batch_size: 128
    wrap: True

#      train:
#        target: ldm.data.imagenet.ImageNetSRTrain
#        params:
#          size: 256
#          degradation: pil_nearest
#      validation:
#        target: ldm.data.imagenet.ImageNetSRValidation
#        params:
#          size: 256
#          degradation: pil_nearest
#
#  lightning:
#    callbacks:
#      image_logger:
#        target: main.ImageLogger
#        params:
#          batch_frequency: 1000
#          max_images: 8
#          increase_log_steps: True

  trainconfig:
    benchmark: True
    accumulate_grad_batches: 2
    base_learning_rate: 4.5e-6
