model:
  config_target: src.models.legacy_model_configs.morphVAEConfig

  ddconfig:
    input_dim: [1, 288, 128]
    n_out_channels: 16
    latent_dim: 128

  lossconfig:
    kld_weight: .1
    metric_weight: 10
    temperature: .1

  dataconfig:
    num_workers: 8
    batch_size: 512
    wrap: True
    root: "/media/nick/hdd021/Cole Trapnell's Lab Dropbox/Nick Lammers/Nick/morphseq/training_data/20241107_ds/"

  trainconfig:
    benchmark: True
    accumulate_grad_batches: 2
    max_epochs: 100

