defaults:
  - _self_
  - model: vae

hydra:
  run:
    # top‐level directory under which *all* runs go
    dir: "/media/nick/hdd021/Cole Trapnell's Lab Dropbox/Nick Lammers/Nick/morphseq/training_data/20241107_ds/training_outputs/${hydra.job.name}_${now:%Y%m%d_%H%M%S}"

  sweep:
    dir: "/media/nick/hdd021/Cole Trapnell's Lab Dropbox/Nick Lammers/Nick/morphseq/training_data/20241107_ds/training_outputs/"
      # create sub-folder 0, 1, 2, … for each combination
    subdir: "${hydra.job.name}_${now:%Y%m%d_%H%M%S}"
