config_target: src.models.model_configs.VAEConfig

ddconfig:
  name: "convVAE"
  input_dim: [1, 288, 128]
  n_out_channels: 16
  latent_dim: 100
  n_conv_layers: 5

lossconfig:
  kld_weight: 10.0
  pips_flag: True
  pips_weight: 1.0
  pips_net: "vgg"

dataconfig:
  target: "BasicDataset"
  num_workers: 8
  batch_size: 512
  wrap: True
  root: ${ancestor:${hydra:run.dir},2} #"/media/nick/hdd021/Cole Trapnell's Lab Dropbox/Nick Lammers/Nick/morphseq/training_data/20241107_ds/"

trainconfig:
  benchmark: True
  accumulate_grad_batches: 2
  max_epochs: 5
  eval_gpu_flag: True