
config_target: src.models.legacy_model_configs.VAEFancyConfig
ckpt_path: "/net/trapnell/vol1/home/nlammers/projects/data/morphseq/outside_models/ldm-kl/ldm_kl4/model.ckpt"

ddconfig:
  name: "ldmVAE"
  latent_dim: 100
  double_z: True
  z_channels: 3
  resolution: [288, 128]
  in_channels: 1
  out_ch: 1
  ch: 128
  ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
  num_res_blocks: 2
  attn_resolutions: [ ]
  dropout: 0.0
  freeze_encoder_trunk: True

lossconfig:
  kld_weight: 5
  pips_flag: True
  pips_weight: 0.8
  pips_net: "vgg"

  # get scheduler info
  schedule_pips: True
  pips_warmup: 7
  pips_rampup: 5

  schedule_kld: True
  kld_warmup: 2
  kld_rampup: 5



dataconfig:
  target: "BasicDataset"
  num_workers: 8
  batch_size: 16
  wrap: True
  root: "/net/trapnell/vol1/home/nlammers/projects/data/morphseq/training_data/20241107_ds/"

trainconfig:
  benchmark: True
  accumulate_grad_batches: 2
  max_epochs: 25

