config_target: src.models.model_configs.VAEConfig

ddconfig:
  name: "DeiT-Tiny" #"Efficient-B0-RA"
  input_dim: [1, 288, 128]
  dec_use_local_attn: False # Currently a bug in this somewhere
  latent_dim: 64
#  n_conv_layers: 5

lossconfig:
  kld_weight: 1.0

  pips_flag: True
  pips_weight: 7.5
  pips_net: "vgg"

  use_gan: True
  gan_weight: 1.0
  gan_net: "patch"

dataconfig:
  target: "BasicDataset"
  num_workers: 8
  batch_size: 64
  wrap: True
  root: ${ancestor:${hydra:run.dir},2} #"/media/nick/hdd021/Cole Trapnell's Lab Dropbox/Nick Lammers/Nick/morphseq/training_data/20241107_ds/"

trainconfig:
  benchmark: True
  accumulate_grad_batches: 1
  max_epochs: 40
  save_epochs: [9, 19, 29]
  eval_gpu_flag: True